// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvDQXjXzpyjv2S_e87REcgaCmYs4eiF9w',
    appId: '1:1041207834421:web:fbf7d37a79c5f5c9ec3e7c',
    messagingSenderId: '1041207834421',
    projectId: 'doan1-df431',
    authDomain: 'doan1-df431.firebaseapp.com',
    databaseURL: 'https://doan1-df431-default-rtdb.firebaseio.com/',
    storageBucket: 'gs://doan1-df431.appspot.com',
    measurementId: 'G-FETH3K1S2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvDQXjXzpyjv2S_e87REcgaCmYs4eiF9w',
    appId: '1:1041207834421:web:fbf7d37a79c5f5c9ec3e7c',
    messagingSenderId: '1041207834421',
    projectId: 'doan1-df431',
    authDomain: 'doan1-df431.firebaseapp.com',
    databaseURL: 'https://doan1-df431-default-rtdb.firebaseio.com/',
    storageBucket: 'gs://doan1-df431.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvDQXjXzpyjv2S_e87REcgaCmYs4eiF9w',
    appId: '1:1041207834421:web:fbf7d37a79c5f5c9ec3e7c',
    messagingSenderId: '1041207834421',
    projectId: 'doan1-df431',
    authDomain: 'doan1-df431.firebaseapp.com',
    databaseURL: 'https://doan1-df431-default-rtdb.firebaseio.com/',
    storageBucket: 'gs://doan1-df431.appspot.com',
    measurementId: 'G-FETH3K1S2K',
  );
}
